Repository meongmory/meongmory_android, pull requests merged in 2023-07, with the labels that each got.

#27 [feature/base] BaseViewModel 셋팅 및 다크테마 제거
  presentation/src/main/java/com/meongmoryteam/presentation/base/BaseViewModel.kt
  presentation/src/main/java/com/meongmoryteam/presentation/base/LoadState.kt
  presentation/src/main/java/com/meongmoryteam/presentation/base/ViewEvent.kt
  presentation/src/main/java/com/meongmoryteam/presentation/base/ViewSideEffect.kt
  presentation/src/main/java/com/meongmoryteam/presentation/base/ViewState.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Shape.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Theme.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Type.kt
Labels: :computer: feat, ssongsik

#29 [feature/mypage] 마이페이지 뷰 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/meongmoryteam/presentation/ui/main/MainScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/MyPageScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/ic_coin.xml
  presentation/src/main/res/drawable/ic_info.xml
  presentation/src/main/res/drawable/ic_left_btn.xml
  presentation/src/main/res/drawable/ic_logout.xml
  presentation/src/main/res/drawable/ic_mail.xml
  presentation/src/main/res/drawable/ic_right_btn.xml
  presentation/src/main/res/drawable/ic_send.xml
  presentation/src/main/res/drawable/ic_unlock.xml
  presentation/src/main/res/drawable/ic_user.xml
  presentation/src/main/res/drawable/myiconpack/IcCrown.kt
  presentation/src/main/res/drawable/myiconpack/IcLeftBtn.kt
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, arin

#24 [feature/register family] 강아지네 추가 페이지 화면 UI 구현
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyForm.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/invitation/RegisterByCodeScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/name/RegisterByNameScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Type.kt
  presentation/src/main/res/drawable-v24/default_profile.png
  presentation/src/main/res/font/applesdgothicneosb.ttf
  presentation/src/main/res/font/inter_black.ttf
  presentation/src/main/res/font/inter_bold.ttf
  presentation/src/main/res/font/inter_extrabold.ttf
  presentation/src/main/res/font/inter_extralight.ttf
  presentation/src/main/res/font/inter_light.ttf
  presentation/src/main/res/font/inter_medium.ttf
  presentation/src/main/res/font/inter_regular.ttf
  presentation/src/main/res/font/inter_semibold.ttf
  presentation/src/main/res/font/inter_thin.ttf
  presentation/src/main/res/font/notosanskr_medium.ttf
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, seuri
