Repository meongmory/meongmory_android, pull requests merged in 2023-08, with the labels that each got.

#33 [feature/register dog] 강아지 등록 화면 UI 구현
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterForm.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/invitation/RegisterByCodeScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/name/RegisterByNameScreen.kt
  presentation/src/main/res/drawable-v24/search.png
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, seuri

#31 [feature/mypage-profile] 마이페이지 프로필, 문의하기 뷰 구현
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/meongmoryteam/presentation/ui/main/MainScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/MyPageScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/profile/MyPageProfileActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/profile/MyPageProfileScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/question/MyPageQuestionActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/myPage/question/MyPageQuestionScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/ic_email_select.xml
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, arin

#40 [refactor/register] 등록 페이지 상태 뷰모델로 리팩토링
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogContract.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_dog/RegisterDogViewModel.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyContract.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterFamilyViewModel.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/RegisterForm.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/invitation/RegisterByCodeScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/register_family/name/RegisterByNameScreen.kt
Labels: :hammer:refact, seuri

#46 [feature/login_phone] 인증번호 화면 구현 및 api 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/meongmoryteam/meongmory/di/NetworkModule.kt
  app/src/main/java/com/meongmoryteam/meongmory/di/RepositoryModule.kt
  data/src/main/java/com/meongmoryteam/data/datasource/FoodDataSource.kt
  data/src/main/java/com/meongmoryteam/data/datasource/FoodDataSourceImpl.kt
  data/src/main/java/com/meongmoryteam/data/datasource/login/LoginDataSource.kt
  data/src/main/java/com/meongmoryteam/data/datasource/login/LoginDataSourceImpl.kt
  data/src/main/java/com/meongmoryteam/data/model/GetWeekFood.kt
  data/src/main/java/com/meongmoryteam/data/model/request/login/SmsSendRequest.kt
  data/src/main/java/com/meongmoryteam/data/model/request/login/SmsValidateRequest.kt
  data/src/main/java/com/meongmoryteam/data/model/response/login/GetSmsSendResponse.kt
  data/src/main/java/com/meongmoryteam/data/model/response/login/PostSmsValidateResponse.kt
  data/src/main/java/com/meongmoryteam/data/repository/FoodRepositoryImpl.kt
  data/src/main/java/com/meongmoryteam/data/repository/login/LoginRepositoryImpl.kt
  data/src/main/java/com/meongmoryteam/data/service/ExampleApi.kt
  data/src/main/java/com/meongmoryteam/data/service/login/LoginApi.kt
  domain/src/main/java/com/meongmoryteam/domain/model/ResponseWeekFoodEntity.kt
  domain/src/main/java/com/meongmoryteam/domain/model/reqeust/login/SmsSendRequestEntity.kt
  domain/src/main/java/com/meongmoryteam/domain/model/reqeust/login/SmsValidateRequestEntity.kt
  domain/src/main/java/com/meongmoryteam/domain/model/response/login/GetSmsSendEntity.kt
  domain/src/main/java/com/meongmoryteam/domain/model/response/login/PostSmsValidateEntity.kt
  domain/src/main/java/com/meongmoryteam/domain/repository/FoodRepository.kt
  domain/src/main/java/com/meongmoryteam/domain/repository/login/LoginRepository.kt
  domain/src/main/java/com/meongmoryteam/domain/usecase/GetWeekFoodUseCase.kt
  domain/src/main/java/com/meongmoryteam/domain/usecase/login/GetSmsSendUseCase.kt
  domain/src/main/java/com/meongmoryteam/domain/usecase/login/PostSmsValidateUseCase.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ExampleFoodState.kt
  presentation/src/main/java/com/meongmoryteam/presentation/MainViewModel.kt
  presentation/src/main/java/com/meongmoryteam/presentation/base/CommonText.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/login/LoginContract.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/meongmoryteam/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik
